---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Test Vector works
    shell: vector --version
  - name: Check Vector config
    shell: vector validate
